n = input('Digite algo:')
print('O tipo primitivo é {}!.'.format(type(n)))
print('Só tem espaços? {}!.'.format(n.isspace()))
print('É um número? {}!.'.format(n.isnumeric()))
print('É alfabético? {}!.'.format(n.isalpha()))
print('É alfanúmerico? {}!.'.format(n.isalnum()))
print('Está em maiusculo? {}!.'.format(n.isupper()))
print('Está em minusculo? {}!.'.format(n.islower()))
print('Está capitalizada? {}!.'.format(n.istitle))