nome = str(input('Digite seu nome completo: ')).strip()
print(f'Olá, {nome}! É um prazer te conhecer!')
print('Irei alterar seu nome vejamos:')
print(nome.upper())
print(nome.lower())
print('Seu nome tem {} Letras'.format(len(nome)))
#print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))
print('Seu nome sem espaços tem {} letras'.format(len(nome) - nome.count(' ')))
separador = nome.split()
print('Seu primero nome é {} e tem {} letras'.format(separador [0], len(separador[0])))